Support for JWT
kapetacom/codegen-target-go pull request #6
Opened 2024-02-05 14:02 UTC by sorenmat

* Did  a bit of clean up of package names.
* Introduced an interface for the services to implmenent.
This is done so we can update the interface definition when adding new
rest methods, and that will give us an not implemented error in the
actual handler with the business code
* Moved generated code from pkg/generated to generated

2024-02-06 09:54 UTC, hofmeister requested changes

2024-02-06 09:54 UTC, hofmeister commented on templates/kapeta/block-type-service/auth-middleware.hbs
> +{{#consumes 'kapeta/resource-type-auth-jwt-consumer'}}
Should  the middleware not also be added if its a provider ?

2024-02-06 09:54 UTC, hofmeister commented on templates/kapeta/block-type-service/main.go.hbs
> +    {{#consumers-of-type 'kapeta/resource-type-auth-jwt-consumer'}}
Middleware for providers ?

2024-02-06 09:54 UTC, hofmeister commented on test/resources/examples/users/generated/services/users_interface.go
> +	CreateUser(ctx echo.Context) error
Any way we can make the request body, path params and query params more type safe?

2024-02-06 11:54 UTC, sorenmat commented on test/resources/examples/users/generated/services/users_interface.go
> +	CreateUser(ctx echo.Context) error
Great idea... Yes, will fix

2024-02-07 14:03 UTC, hofmeister approved these changes
Looking good - just minor naming comment

2024-02-07 16:17 UTC, merged